### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by thekevinbrown** [paragonie/ciphersweet-js#14]
We'd like to get our PR (#11) merged. Is anybody monitoring this repository? Is there anything we can do to help here?

**Comment by paragonie-security** [comment]
Unfortunately, we've had a lot of high priority work since February and this fell through the cracks. We'll get a release out before the end of the week.

**Comment by thekevinbrown** [comment]
Awesome, thanks for your help guys!
