### ISSUE TITLE
Bug with asyncness in EncryptedField.getBlindIndex

### ISSUE THREAD

**Issue by G1gg1L3s** [paragonie/ciphersweet-js#20]
Look at this [line](https://github.com/paragonie/ciphersweet-js/blob/ff9052c02ed8393bcd7493d138cf32ffe75bcab9/lib/encryptedfield.js#L156):
```js
return this.getBlindIndexRaw(plaintext, name, key).toString('hex');
```
`this.getBlindIndexRaw` is the async method, so it returns the `Promise`. The issue is that if you call `toString` on a promise, it always returns the string `'[object Promise]'`. And that string is always returned as the blind index!

It probably should be something like:
```js
return (await this.getBlindIndexRaw(plaintext, name, key)).toString('hex');
```

I didn't check other code, so there could be more places like this.

**Comment by paragonie-security** [comment]
We checked and that was the only place it wasn't wrapped in an `await` call.
