### ISSUE TITLE
Incorporate TypeScript Types?

### ISSUE THREAD

**Issue by thekevinbrown** [paragonie/ciphersweet-js#9]
Hey there,

We're using TypeScript for our backend, and have built a set of TypeScript types for this library. Would you be interested in merging them into the library package proper and taking on maintenance of them, or would you prefer that we contribute them to https://github.com/DefinitelyTyped/DefinitelyTyped and try to keep them in sync as a community effort?

We're happy to go either way, but it's awesome for the TypeScript community when the types come down with the library in a single npm install, so that's the preferred approach in general.

**Comment by paragonie-security** [comment]
Please send them to us, we'll keep them up-to-date with any future library changes.

**Comment by thekevinbrown** [comment]
Sounds good! Just created #10.

**Comment by paragonie-security** [comment]
TypeScript support is released in `v1.3.0`.

**Comment by thekevinbrown** [comment]
Awesome, thank you, will upgrade and give it a go!
